CREATE TABLE actor (
    actor_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name varchar(45) NOT NULL,
    last_name varchar(45) NOT NULL,
    last_update timestamp NOT NULL DEFAULT now()
);

CREATE INDEX idx_actor_last_name ON actor (last_name);

CREATE TRIGGER last_updated
    BEFORE UPDATE ON actor
    FOR EACH ROW
    EXECUTE PROCEDURE last_updated();
