CREATE TABLE address (
    address_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    address varchar(50) NOT NULL,
    address2 varchar(50),
    district varchar(20) NOT NULL,
    city_id integer NOT NULL,
    postal_code varchar(10),
    phone varchar(20) NOT NULL,
    last_update timestamp NOT NULL DEFAULT now(),
    CONSTRAINT address_city_id_fkey
        FOREIGN KEY (city_id) REFERENCES city(city_id)
);

CREATE INDEX idx_fk_city_id ON address (city_id);

CREATE TRIGGER last_updated
    BEFORE UPDATE ON address
    FOR EACH ROW
    EXECUTE PROCEDURE last_updated();
