CREATE TABLE city (
    city_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    city varchar(50) NOT NULL,
    country_id integer NOT NULL,
    last_update timestamp NOT NULL DEFAULT now(),
    CONSTRAINT city_country_id_fkey
        FOREIGN KEY (country_id) REFERENCES country(country_id)
);

CREATE INDEX idx_fk_country_id ON city (country_id);

CREATE TRIGGER last_updated
    BEFORE UPDATE ON city
    FOR EACH ROW
    EXECUTE PROCEDURE last_updated();
