CREATE TABLE country (
    country_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    country varchar(50) NOT NULL,
    last_update timestamp NOT NULL DEFAULT now()
);

CREATE TRIGGER last_updated
    BEFORE UPDATE ON country
    FOR EACH ROW
    EXECUTE PROCEDURE last_updated();
