CREATE TABLE customer (
    customer_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id integer NOT NULL,
    first_name varchar(45) NOT NULL,
    last_name varchar(45) NOT NULL,
    email varchar(50),
    address_id integer NOT NULL,
    activebool boolean NOT NULL DEFAULT true,
    create_date date NOT NULL DEFAULT CURRENT_DATE,
    last_update timestamp DEFAULT now(),
    active integer,
    CONSTRAINT customer_store_id_fkey
        FOREIGN KEY (store_id) REFERENCES store(store_id),
    CONSTRAINT customer_address_id_fkey
        FOREIGN KEY (address_id) REFERENCES address(address_id)
);

CREATE INDEX idx_fk_store_id ON customer (store_id);
CREATE INDEX idx_fk_address_id ON customer (address_id);
CREATE INDEX idx_last_name ON customer (last_name);

CREATE TRIGGER last_updated
    BEFORE UPDATE ON customer
    FOR EACH ROW
    EXECUTE PROCEDURE last_updated();
