CREATE TABLE film (
    film_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title varchar(255) NOT NULL,
    description text,
    release_year integer,
    language_id integer NOT NULL,
    original_language_id integer,
    rental_duration smallint NOT NULL DEFAULT 3,
    rental_rate numeric(4,2) NOT NULL DEFAULT 4.99,
    length smallint,
    replacement_cost numeric(5,2) NOT NULL DEFAULT 19.99,
    rating mpaa_rating DEFAULT 'G',
    last_update timestamp NOT NULL DEFAULT now(),
    special_features text[],
    fulltext tsvector NOT NULL,
    CONSTRAINT film_language_id_fkey
        FOREIGN KEY (language_id) REFERENCES language(language_id),
    CONSTRAINT film_original_language_id_fkey
        FOREIGN KEY (original_language_id) REFERENCES language(language_id)
);

CREATE INDEX idx_title ON film (title);
CREATE INDEX idx_fk_language_id ON film (language_id);
CREATE INDEX idx_fk_original_language_id ON film (original_language_id);
CREATE INDEX film_fulltext_idx ON film USING gist(fulltext);

CREATE TRIGGER film_fulltext_trigger
    BEFORE INSERT OR UPDATE ON film
    FOR EACH ROW
    EXECUTE PROCEDURE
      tsvector_update_trigger('fulltext', 'pg_catalog.english', 'title', 'description');

CREATE TRIGGER last_updated
    BEFORE UPDATE ON film
    FOR EACH ROW
    EXECUTE PROCEDURE last_updated();
