CREATE TABLE inventory (
    inventory_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_id integer NOT NULL,
    store_id integer NOT NULL,
    last_update timestamp NOT NULL DEFAULT now(),
    CONSTRAINT inventory_film_id_fkey
        FOREIGN KEY (film_id) REFERENCES film(film_id),
    CONSTRAINT inventory_store_id_fkey
        FOREIGN KEY (store_id) REFERENCES store(store_id)
);

CREATE INDEX idx_store_id_film_id ON inventory (store_id, film_id);

CREATE TRIGGER last_updated
    BEFORE UPDATE ON inventory
    FOR EACH ROW
    EXECUTE PROCEDURE last_updated();
