CREATE TABLE language (
    language_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name char(20) NOT NULL,
    last_update timestamp NOT NULL DEFAULT now()
);

CREATE TRIGGER last_updated
    BEFORE UPDATE ON language
    FOR EACH ROW
    EXECUTE PROCEDURE last_updated();
