CREATE TABLE payment (
    payment_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id integer NOT NULL,
    staff_id integer NOT NULL,
    rental_id integer NOT NULL,
    amount numeric(5,2) NOT NULL,
    payment_date timestamp NOT NULL,
    CONSTRAINT payment_customer_id_fkey
        FOREIGN KEY (customer_id) REFERENCES customer(customer_id)
);

CREATE INDEX idx_fk_customer_id ON payment (customer_id);
CREATE INDEX idx_fk_staff_id ON payment (staff_id);
