CREATE TABLE rental (
    rental_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rental_date timestamp NOT NULL,
    inventory_id integer NOT NULL,
    customer_id integer NOT NULL,
    return_date timestamp,
    staff_id integer NOT NULL,
    last_update timestamp NOT NULL DEFAULT now(),
    CONSTRAINT rental_inventory_id_fkey
        FOREIGN KEY (inventory_id) REFERENCES inventory(inventory_id),
    CONSTRAINT rental_customer_id_fkey
        FOREIGN KEY (customer_id) REFERENCES customer(customer_id),
    CONSTRAINT rental_staff_id_fkey
        FOREIGN KEY (staff_id) REFERENCES staff(staff_id)
);

CREATE UNIQUE INDEX idx_unq_rental_rental_date_inventory_id_customer_id
    ON rental(rental_date, inventory_id, customer_id);

CREATE INDEX idx_fk_inventory_id ON rental (inventory_id);
CREATE INDEX idx_fk_customer_id ON rental (customer_id);
CREATE INDEX idx_fk_staff_id ON rental (staff_id);

CREATE TRIGGER last_updated
    BEFORE UPDATE ON rental
    FOR EACH ROW
    EXECUTE PROCEDURE last_updated();
