CREATE TABLE staff (
    staff_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name varchar(45) NOT NULL,
    last_name varchar(45) NOT NULL,
    address_id integer NOT NULL,
    email varchar(50),
    store_id integer NOT NULL,
    active boolean NOT NULL DEFAULT true,
    username varchar(16) NOT NULL,
    password varchar(40),
    last_update timestamp NOT NULL DEFAULT now(),
    picture bytea,
    CONSTRAINT staff_address_id_fkey
        FOREIGN KEY (address_id) REFERENCES address(address_id),
    CONSTRAINT staff_store_id_fkey
        FOREIGN KEY (store_id) REFERENCES store(store_id)
);

CREATE INDEX idx_fk_address_id ON staff (address_id);
CREATE INDEX idx_fk_store_id ON staff (store_id);

CREATE TRIGGER last_updated
    BEFORE UPDATE ON staff
    FOR EACH ROW
    EXECUTE PROCEDURE last_updated();
