CREATE TABLE store (
    store_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    manager_staff_id integer NOT NULL,
    address_id integer NOT NULL,
    last_update timestamp NOT NULL DEFAULT now(),
    CONSTRAINT store_manager_staff_id_fkey
        FOREIGN KEY (manager_staff_id) REFERENCES staff(staff_id),
    CONSTRAINT store_address_id_fkey
        FOREIGN KEY (address_id) REFERENCES address(address_id)
);

CREATE UNIQUE INDEX idx_unq_manager_staff_id
    ON store(manager_staff_id);

CREATE TRIGGER last_updated
    BEFORE UPDATE ON store
    FOR EACH ROW
    EXECUTE PROCEDURE last_updated();
