#include "../test_framework.h"
#include "parser.h"
#include "pg_create_table.h"
#include <string.h>

/* Test: Parse INTEGER column */
TEST_CASE(parser_columns, parse_column_int) {
    Parser *parser = parser_create("CREATE TABLE t (id INTEGER);");
    ASSERT_NOT_NULL(parser);

    CreateTableStmt *stmt = parser_parse_create_table(parser);
    ASSERT_NOT_NULL(stmt);

    parser_destroy(parser);
    free_create_table_stmt(stmt);
    TEST_PASS();
}

/* Test: Parse VARCHAR column */
TEST_CASE(parser_columns, parse_column_varchar) {
    Parser *parser = parser_create("CREATE TABLE t (name VARCHAR(100));");
    ASSERT_NOT_NULL(parser);

    CreateTableStmt *stmt = parser_parse_create_table(parser);
    ASSERT_NOT_NULL(stmt);

    parser_destroy(parser);
    free_create_table_stmt(stmt);
    TEST_PASS();
}

/* Test: Parse NUMERIC column with precision and scale */
TEST_CASE(parser_columns, parse_column_numeric) {
    Parser *parser = parser_create("CREATE TABLE t (price NUMERIC(10, 2));");
    ASSERT_NOT_NULL(parser);

    CreateTableStmt *stmt = parser_parse_create_table(parser);
    ASSERT_NOT_NULL(stmt);

    parser_destroy(parser);
    free_create_table_stmt(stmt);
    TEST_PASS();
}

/* Test: Parse TEXT column */
TEST_CASE(parser_columns, parse_column_text) {
    Parser *parser = parser_create("CREATE TABLE t (description TEXT);");
    ASSERT_NOT_NULL(parser);

    CreateTableStmt *stmt = parser_parse_create_table(parser);
    ASSERT_NOT_NULL(stmt);

    parser_destroy(parser);
    free_create_table_stmt(stmt);
    TEST_PASS();
}

/* Test: Parse array type */
TEST_CASE(parser_columns, parse_column_array) {
    Parser *parser = parser_create("CREATE TABLE t (tags TEXT[]);");
    ASSERT_NOT_NULL(parser);

    CreateTableStmt *stmt = parser_parse_create_table(parser);
    ASSERT_NOT_NULL(stmt);

    parser_destroy(parser);
    free_create_table_stmt(stmt);
    TEST_PASS();
}

/* Test: Parse NOT NULL constraint */
TEST_CASE(parser_columns, parse_column_not_null) {
    Parser *parser = parser_create("CREATE TABLE t (name VARCHAR(50) NOT NULL);");
    ASSERT_NOT_NULL(parser);

    CreateTableStmt *stmt = parser_parse_create_table(parser);
    ASSERT_NOT_NULL(stmt);

    parser_destroy(parser);
    free_create_table_stmt(stmt);
    TEST_PASS();
}

/* Test: Parse DEFAULT constraint */
TEST_CASE(parser_columns, parse_column_default) {
    Parser *parser = parser_create("CREATE TABLE t (status VARCHAR(20) DEFAULT 'active');");
    ASSERT_NOT_NULL(parser);

    CreateTableStmt *stmt = parser_parse_create_table(parser);
    ASSERT_NOT_NULL(stmt);

    parser_destroy(parser);
    free_create_table_stmt(stmt);
    TEST_PASS();
}

/* Test: Parse DEFAULT with function */
TEST_CASE(parser_columns, parse_column_default_function) {
    Parser *parser = parser_create("CREATE TABLE t (created_at TIMESTAMP DEFAULT now());");
    ASSERT_NOT_NULL(parser);

    CreateTableStmt *stmt = parser_parse_create_table(parser);
    ASSERT_NOT_NULL(stmt);

    parser_destroy(parser);
    free_create_table_stmt(stmt);
    TEST_PASS();
}

/* Test: Parse GENERATED ALWAYS AS IDENTITY */
TEST_CASE(parser_columns, parse_column_generated_identity) {
    Parser *parser = parser_create("CREATE TABLE t (id INTEGER GENERATED ALWAYS AS IDENTITY);");
    ASSERT_NOT_NULL(parser);

    CreateTableStmt *stmt = parser_parse_create_table(parser);
    ASSERT_NOT_NULL(stmt);

    parser_destroy(parser);
    free_create_table_stmt(stmt);
    TEST_PASS();
}

/* Test: Parse GENERATED BY DEFAULT AS IDENTITY */
TEST_CASE(parser_columns, parse_column_generated_by_default) {
    Parser *parser = parser_create("CREATE TABLE t (id INTEGER GENERATED BY DEFAULT AS IDENTITY);");
    ASSERT_NOT_NULL(parser);

    CreateTableStmt *stmt = parser_parse_create_table(parser);
    ASSERT_NOT_NULL(stmt);

    parser_destroy(parser);
    free_create_table_stmt(stmt);
    TEST_PASS();
}

/* Test: Parse STORAGE clause */
TEST_CASE(parser_columns, parse_column_storage) {
    Parser *parser = parser_create("CREATE TABLE t (data TEXT STORAGE EXTERNAL);");
    ASSERT_NOT_NULL(parser);

    CreateTableStmt *stmt = parser_parse_create_table(parser);
    ASSERT_NOT_NULL(stmt);

    parser_destroy(parser);
    free_create_table_stmt(stmt);
    TEST_PASS();
}

/* Test: Parse COMPRESSION clause */
TEST_CASE(parser_columns, parse_column_compression) {
    Parser *parser = parser_create("CREATE TABLE t (data TEXT COMPRESSION pglz);");
    ASSERT_NOT_NULL(parser);

    CreateTableStmt *stmt = parser_parse_create_table(parser);
    ASSERT_NOT_NULL(stmt);

    parser_destroy(parser);
    free_create_table_stmt(stmt);
    TEST_PASS();
}

/* Test: Parse COLLATE clause */
TEST_CASE(parser_columns, parse_column_collate) {
    Parser *parser = parser_create("CREATE TABLE t (name VARCHAR(100) COLLATE \"en_US\");");
    ASSERT_NOT_NULL(parser);

    CreateTableStmt *stmt = parser_parse_create_table(parser);
    ASSERT_NOT_NULL(stmt);

    parser_destroy(parser);
    free_create_table_stmt(stmt);
    TEST_PASS();
}

/* Test: Parse multiple column constraints */
TEST_CASE(parser_columns, parse_multiple_constraints) {
    Parser *parser = parser_create(
        "CREATE TABLE t (name VARCHAR(100) NOT NULL DEFAULT 'unknown' UNIQUE);"
    );
    ASSERT_NOT_NULL(parser);

    CreateTableStmt *stmt = parser_parse_create_table(parser);
    ASSERT_NOT_NULL(stmt);

    parser_destroy(parser);
    free_create_table_stmt(stmt);
    TEST_PASS();
}

/* Test: Parse BIGINT type */
TEST_CASE(parser_columns, parse_column_bigint) {
    Parser *parser = parser_create("CREATE TABLE t (big_id BIGINT);");
    ASSERT_NOT_NULL(parser);

    CreateTableStmt *stmt = parser_parse_create_table(parser);
    ASSERT_NOT_NULL(stmt);

    parser_destroy(parser);
    free_create_table_stmt(stmt);
    TEST_PASS();
}

/* Test: Parse SMALLINT type */
TEST_CASE(parser_columns, parse_column_smallint) {
    Parser *parser = parser_create("CREATE TABLE t (small_num SMALLINT);");
    ASSERT_NOT_NULL(parser);

    CreateTableStmt *stmt = parser_parse_create_table(parser);
    ASSERT_NOT_NULL(stmt);

    parser_destroy(parser);
    free_create_table_stmt(stmt);
    TEST_PASS();
}

/* Test: Parse BOOLEAN type */
TEST_CASE(parser_columns, parse_column_boolean) {
    Parser *parser = parser_create("CREATE TABLE t (is_active BOOLEAN);");
    ASSERT_NOT_NULL(parser);

    CreateTableStmt *stmt = parser_parse_create_table(parser);
    ASSERT_NOT_NULL(stmt);

    parser_destroy(parser);
    free_create_table_stmt(stmt);
    TEST_PASS();
}

/* Test: Parse TIMESTAMP type */
TEST_CASE(parser_columns, parse_column_timestamp) {
    Parser *parser = parser_create("CREATE TABLE t (created_at TIMESTAMP);");
    ASSERT_NOT_NULL(parser);

    CreateTableStmt *stmt = parser_parse_create_table(parser);
    ASSERT_NOT_NULL(stmt);

    parser_destroy(parser);
    free_create_table_stmt(stmt);
    TEST_PASS();
}

/* Test: Parse DATE type */
TEST_CASE(parser_columns, parse_column_date) {
    Parser *parser = parser_create("CREATE TABLE t (birth_date DATE);");
    ASSERT_NOT_NULL(parser);

    CreateTableStmt *stmt = parser_parse_create_table(parser);
    ASSERT_NOT_NULL(stmt);

    parser_destroy(parser);
    free_create_table_stmt(stmt);
    TEST_PASS();
}

/* Test: Parse JSONB type */
TEST_CASE(parser_columns, parse_column_jsonb) {
    Parser *parser = parser_create("CREATE TABLE t (data JSONB);");
    ASSERT_NOT_NULL(parser);

    CreateTableStmt *stmt = parser_parse_create_table(parser);
    ASSERT_NOT_NULL(stmt);

    parser_destroy(parser);
    free_create_table_stmt(stmt);
    TEST_PASS();
}

/* Test: Parse UUID type */
TEST_CASE(parser_columns, parse_column_uuid) {
    Parser *parser = parser_create("CREATE TABLE t (id UUID);");
    ASSERT_NOT_NULL(parser);

    CreateTableStmt *stmt = parser_parse_create_table(parser);
    ASSERT_NOT_NULL(stmt);

    parser_destroy(parser);
    free_create_table_stmt(stmt);
    TEST_PASS();
}

/* Test suite definition */
static TestCase parser_columns_tests[] = {
    {"parse_column_int", test_parser_columns_parse_column_int, "parser_columns"},
    {"parse_column_varchar", test_parser_columns_parse_column_varchar, "parser_columns"},
    {"parse_column_numeric", test_parser_columns_parse_column_numeric, "parser_columns"},
    {"parse_column_text", test_parser_columns_parse_column_text, "parser_columns"},
    {"parse_column_array", test_parser_columns_parse_column_array, "parser_columns"},
    {"parse_column_not_null", test_parser_columns_parse_column_not_null, "parser_columns"},
    {"parse_column_default", test_parser_columns_parse_column_default, "parser_columns"},
    {"parse_column_default_function", test_parser_columns_parse_column_default_function, "parser_columns"},
    {"parse_column_generated_identity", test_parser_columns_parse_column_generated_identity, "parser_columns"},
    {"parse_column_generated_by_default", test_parser_columns_parse_column_generated_by_default, "parser_columns"},
    {"parse_column_storage", test_parser_columns_parse_column_storage, "parser_columns"},
    {"parse_column_compression", test_parser_columns_parse_column_compression, "parser_columns"},
    {"parse_column_collate", test_parser_columns_parse_column_collate, "parser_columns"},
    {"parse_multiple_constraints", test_parser_columns_parse_multiple_constraints, "parser_columns"},
    {"parse_column_bigint", test_parser_columns_parse_column_bigint, "parser_columns"},
    {"parse_column_smallint", test_parser_columns_parse_column_smallint, "parser_columns"},
    {"parse_column_boolean", test_parser_columns_parse_column_boolean, "parser_columns"},
    {"parse_column_timestamp", test_parser_columns_parse_column_timestamp, "parser_columns"},
    {"parse_column_date", test_parser_columns_parse_column_date, "parser_columns"},
    {"parse_column_jsonb", test_parser_columns_parse_column_jsonb, "parser_columns"},
    {"parse_column_uuid", test_parser_columns_parse_column_uuid, "parser_columns"},
};

void run_parser_columns_tests(void) {
    run_test_suite("parser_columns", NULL, NULL, parser_columns_tests,
                   sizeof(parser_columns_tests) / sizeof(parser_columns_tests[0]));
}
